simple_store/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :catalogs do
    resources :categories
    resources :products
  end

  namespace :api do 
    namespace :v1 do 
      resources :products, only: [:index, :show]
    end
  end

  root 'welcome#index'

end

simple_store/app/models/apparel.rb
class Apparel < Product
end

simple_store/app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :products
  has_many :categories

  has_many :images, as: :imageable
  accepts_nested_attributes_for :images

  validates :name, presence: true, uniqueness: true


end

simple_store/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :catalog

  has_many :sub_categories, class_name: "Category", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Category"

  has_and_belongs_to_many :products

  has_many :images, as: :imageable
end

simple_store/app/models/cutlery.rb
class Cutlery < Product
end

simple_store/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  mount_uploader :image, ImageUploader
end

simple_store/app/models/luggage.rb
class Luggage < Product
end

simple_store/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :catalog

  has_and_belongs_to_many :categories

  has_many :images, as: :imageable
end

simple_store/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

simple_store/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

simple_store/app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :do_we_have_a_logged_in_admin_user?
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
  end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
    @catalog.images.build
  end

  # GET /catalogs/1/edit
  def edit
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params.permit(:name, :active))

    respond_to do |format|
      if @catalog.save

        # Now Lets save some images
        if params["catalog"]["images"]
          params["catalog"]["images"]["image"].each do |image|
            Image.create(imageable_id: @catalog.id, imageable_type: "Catalog", image: image)
          end
        end

        format.html { redirect_to catalogs_path, notice: 'Catalog was successfully created.' }
        format.json { render :show, status: :created, location: @catalog }
      else
        format.html { render :new }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to @catalog, notice: 'Catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @catalog }
      else
        format.html { render :edit }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to catalogs_url, notice: 'Catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalog_params
      params[:catalog].permit(:name, :active, images: [:image]) 
    end

    def do_we_have_a_logged_in_admin_user?
      unless current_user and current_user.admin
        flash[:notice] = "You need to be logged in as an administrator to access this feature"
        redirect_to root_path 
      end
    end
end

simple_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

simple_store/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @catalog = Catalog.last
  end
end

simple_store/app/helpers/catalogs_helper.rb
module CatalogsHelper
end

simple_store/app/helpers/products_helper.rb
module ProductsHelper
end

simple_store/app/views/catalogs/_form.html.erb
<div class="row">
  <div class="col-md-10">
    <%= form_for(:catalog, url: catalogs_path, html: { :class => "form-horizontal"}) do |f| %>
      <% if @catalog.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@catalog.errors.count, "error") %> prohibited this catalog from being saved:</h2>

          <ul>
          <% @catalog.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label "Name", class: "col-sm-2 control-label" %>
        <%= f.text_field :name %>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2">
          <%= f.label "Active" %>
          <%= f.radio_button :active, true, :checked => true, :value => true %>
          <%= f.label "Inactive" %>
          <%= f.radio_button :active, false, :value => false %>
        </div>
      </div>


      <%= f.fields_for :images do |image_fields| %>
        <div class="form-group">
          <%= image_fields.label :images, class: "col-sm-2 control-label" %>
          <%= image_fields.file_field :image, :multiple => true, :class => "btn btn-info" %>
        </div>
      <% end -%>

      <div class="form-group">
        <div class="col-sm-offset-2">
          <%= f.submit "Add", :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

simple_store/app/views/catalogs/edit.html.erb
<h1>Editing Catalog</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalog %> |
<%= link_to 'Back', catalogs_path %>

simple_store/app/views/catalogs/index.html.erb
<% if notice %>
  <div class="alert alert-success">
    <p id="notice"><%= notice %></p>
  </div>
<% end -%>

<h1>Listing Catalogs</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @catalogs.each do |catalog| %>
      <tr>
        <td><%= link_to "#{catalog.name}", catalog %></td>
        <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
        <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catalog', new_catalog_path %>

simple_store/app/views/catalogs/new.html.erb
<h1>New Catalog</h1>

<%= render 'form' %>

<%= link_to 'Back', catalogs_path %>

simple_store/app/views/catalogs/show.html.erb
<div class="alert alert-success">
  <p id="notice">
    <%= notice %>
  </p>
</div>

<%= @catalog.name %>
<br />
<%= link_to 'Edit', edit_catalog_path(@catalog) %> |
<%= link_to 'Back', catalogs_path %>

simple_store/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <a class="navbar-brand" href="/">Simple Store</a>
    <% if user_signed_in? -%>
      <p class="navbar-text navbar-right"><%= logged_in_welcome_message %>
        |
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
      </p>
    <% else -%>
      <p class="navbar-text navbar-right">
        <%= link_to "Sign In", new_user_session_path %>
        |
        <%= link_to "Sign Up", new_user_registration_path %>
      </p>
    <% end -%>
    </div>
  </div>
</nav>

simple_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleStore</title>
  <meta name="viewport", content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

simple_store/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

simple_store/app/views/products/_short_list.html.erb
<div class="col-md-3 product-list <%=type.downcase %>">
  <h3><%= type %></h3>
  <%#= image_tag @catalog.images.first.image_url(:short_wide) %>
  <%#= image_tag @catalog.images[index].image_url(:short_wide) %>
  <ul>
  <% type.constantize.all.each_with_index do |product, i| -%>
    <% if product.is_a?(Apparel) and i == 0 -%>
      <li><%= link_to product.name, "#", id: "featured-apparel-product", data_product_id: product.id %></li>
    <% else -%>
      <li><%= product.name %></li>
    <% end -%>
  <% end -%>
  </ul>
</div>

simple_store/app/views/products/_types_in_a_row.html.erb
<div class="row">
  <%= render partial: "products/short_list", locals: { type: "Apparel", index: 1 } %>
  <%= render partial: "products/short_list", locals: { type: "Luggage", index: 2 } %>
  <%= render partial: "products/short_list", locals: { type: "Cutlery", index: 3 } %>
  <div class="col-md-6 apparel-featured" style="display:none;">
    <p>Featured Apparel Product</p>
  </div>  
</div>

simple_store/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

simple_store/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

simple_store/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

simple_store/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

simple_store/app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-offset-2">
  <h1>Welcome to the Simple Store</h1>
  <% if flash[:notice] %>
    <div class="alert alert-warning">
      <p><%= flash[:notice] %></p>
    </div>
  <% end -%>
    <%#= image_tag @catalog.images.first.image_url(:featured) %> 
    <br />
    <% if user_signed_in? %>
      <%= render partial: "products/types_in_a_row" %>
    <% else -%>
      <p>While we work on building our catalog, please <%= link_to "sign up", new_user_registration_path %></p>
      <br />
      <p>If you already have an account, please <%= link_to "Sign In", new_user_session_path %></p>
    <% end -%>
  </div>
</div>