project_tracking/config/routes.rb
Rails.application.routes.draw do
  resources :topics

  resources :projects do
    collection do 
      get 'search' # TO SHOW THE FORM
      post 'results' # TO PROCESS THE SEARCH
    end
    member do 
      get 'list_topics'
      post 'assign_topics'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  root 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/people' => 'people#index'
  get '/me' => 'people#me'

  post '/me/update_topics' => 'people#update_topics'

end

project_tracking/app/models/project.rb
require 'topical'

class Project < ActiveRecord::Base
  has_and_belongs_to_many :topics

  include Utilities::Topical

  def who_am_i
    self
  end

  def self.find_fun_projects
    fun_projects = []

    Project.all.each do |p| 
      if p.is_related_to?("Ruby on Rails") and p.is_related_to?("BackboneJS")
        fun_projects << p   
      end
    end

    fun_projects
  end

  def self.search(keywords, *attributes)
    project_list = []
    attributes.each do |attribute|
      matching_projects = Project.where("#{attribute.to_s} REGEXP '#{keywords}'")
      matching_projects.each do |project|
        project_list << project
      end
    end
    project_list
  end
end

project_tracking/app/models/topic.rb
class Topic < ActiveRecord::Base
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :users
end

project_tracking/app/models/user.rb
require 'topical'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         # :confirmable

  has_and_belongs_to_many :topics

  # validates :password, 
  #           format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).+\z/,
  #                     message: "needs at least one upper case, one lower case and one number" }

  include Utilities::Topical

  def full_name
    "#{first_name} #{last_name}"
  end

  def matching_projects
    matched_projects = []
    topics.each do |topic|
      Project.all.each do |project|
        if project.is_related_to?(topic.title)
          matched_projects << {project: project, topic: topic}
        end
      end
    end
    matched_projects
  end
end

project_tracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

project_tracking/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def me
  end

  def index
    @users = User.all
  end

  def update_topics
  end
end

project_tracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :list_topics]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save

        ProjectMailer.project_created(current_user, @project).deliver_now

        # ProjectWorker.perform_project_match_async(@project)

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list_topics
  end

  def search
  end

  def results
    @projects = Project.search(params[:keyword], :title, :description)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :start_date)
    end
end

project_tracking/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title)
    end
end

project_tracking/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    puts request.env["omniauth.auth"]
    redirect_to root_path
  end
end

project_tracking/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

project_tracking/app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in_welcome_message
    "Welcome #{current_user.first_name}"
  end
end

project_tracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

project_tracking/app/helpers/topics_helper.rb
module TopicsHelper
end

project_tracking/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <a class="navbar-brand" href="/">Project Tracking</a>
    <% if user_signed_in? -%>
      <p class="navbar-text navbar-right"><%= link_to logged_in_welcome_message, me_path %>
        |
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
      </p>
    <% else -%>
      <p class="navbar-text navbar-right">
        <%= link_to "Sign In", new_user_session_path %>
        |
        <%= link_to "Sign Up", new_user_registration_path %>
        |
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      </p>
    <% end -%>
    <ul class="nav nav-pills">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "People", people_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
    </ul>
  </div>  
</nav>

project_tracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectTracking</title>
  <meta name="viewport", content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container fluid">
    <%= yield %>
  </div>

</body>
</html>

project_tracking/app/views/people/_my_topics.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-2">

    <p id="notice"><%= notice %></p>

    <%= form_tag(me_update_topics_path) do %>

      <div class="row">
        <div class="col-md-3">
          <h3>All Topics</h3>
          <%= select_tag "all_topics", 
                         options_from_collection_for_select(Topic.all, "id", "title"),
                         multiple: true %>
        </div>
        <div class="col-md-3">
          <div class="btn-group-vertical" id="topic-assign-buttons">
            <button class="btn btn-primary">Assign >> </button>
            <button class="btn btn-primary">Remove << </button>
          </div>
        </div>
        <div class="col-md-3">
          <h3>Project Topics</h3>
          <%= select_tag "my_topics",
                         options_from_collection_for_select(current_user.topics, "id", "title"),
                         prompt: "Assign one more topics",
                         multiple: true %>
        </div>
      </div>

    <% end -%>

  </div>
</div>

project_tracking/app/views/people/me.html.erb
<div class="row">
  <h1><%= current_user.full_name %></h1>

  <%= render partial: "people/my_topics" %>
  <hr />
  <h2>My Topic Summary</h2>
  <p><%= current_user.pretty_print_topics %></p>
  <hr />
  <h2>Matching Projects</h2>
  <ul>
  <% current_user.matching_projects.each do |matched_project| -%>
    <li><%= matched_project[:project].title %> based on <%= matched_project[:topic].title %></li>
  <% end -%>

</div>

project_tracking/app/views/projects/_form.html.erb
<%= form_for(@project, html: { :class => "form-horizontal" }) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :start_date, class: "col-sm-2 control-label" %>
    <%= f.date_select :start_date %>
  </div>
  <div class="form-submit">
    <div class="col-sm-offset-2">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

project_tracking/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

project_tracking/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Listing Projects</h1> -->
<h1><%= I18n.t :listing_projects %></h1>

<hr />
<h2><%= I18n.t :fun_projects %></h2>
<ul>
  <% Project.find_fun_projects.each do |fun_project| -%>
  <li><%= fun_project.title %></li>
  <% end -%>
</ul>
<hr />

<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t :title %></th>
      <th><%= I18n.t :description %></th>
      <th><%= I18n.t :start_date %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= I18n.l project.start_date %></td>
        <td><%= link_to "#{I18n.t :show}", project %></td>
        <td><%= link_to "#{I18n.t :edit}", edit_project_path(project) %></td>
        <td><%= link_to "#{I18n.t :topics}", list_topics_project_path(project) %></td>
        <td><%= link_to "#{I18n.t :destroy}", project, method: :delete, data: { confirm: "#{I18n.t :areyousure}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{I18n.t :new_project}", new_project_path %>

project_tracking/app/views/projects/list_topics.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-2">

    <p id="notice"><%= notice %></p>

    <h2>
      <strong>Title:</strong>
      <%= @project.title %>
    </h2>

    <%= form_tag(assign_topics_project_path(@project)) do %>

      <div class="row">
        <div class="col-md-3">
          <h3>All Topics</h3>
          <%= select_tag "all_topics", 
                         options_from_collection_for_select(Topic.all, "id", "title"),
                         multiple: true %>
        </div>
        <div class="col-md-3">
          <div class="btn-group-vertical" id="topic-assign-buttons">
            <button class="btn btn-primary">Assign >> </button>
            <button class="btn btn-primary">Remove << </button>
          </div>
        </div>
        <div class="col-md-3">
          <h3>Project Topics</h3>
          <%= select_tag "project_topics",
                         options_from_collection_for_select(@project.topics, "id", "title"),
                         prompt: "Assign one more topics",
                         multiple: true %>
        </div>
      </div>

    <% end -%>

  </div>
</div>

project_tracking/app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-2">
    <h1>New Project</h1>

    <%= render 'form' %>

    <%= link_to 'Back', projects_path %>
  </div>
</div>

project_tracking/app/views/projects/results.html.erb
<table class="table">
  <thead>
    <tr>
      <th><%= I18n.t :title %></th>
      <th><%= I18n.t :description %></th>
      <th><%= I18n.t :start_date %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= I18n.l project.start_date %></td>
        <td><%= link_to "#{I18n.t :show}", project %></td>
        <td><%= link_to "#{I18n.t :edit}", edit_project_path(project) %></td>
        <td><%= link_to "#{I18n.t :topics}", list_topics_project_path(project) %></td>
        <td><%= link_to "#{I18n.t :destroy}", project, method: :delete, data: { confirm: "#{I18n.t :areyousure}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

project_tracking/app/views/projects/search.html.erb
<h1><%= I18n.t :search_projects %></h1>

<%= form_tag('/projects/results') do -%>
  <%= text_field_tag :keyword, '', size: 40, placeholder: "#{I18n.t :search_prompt}" %>
  <%= submit_tag "#{I18n.t :search}", class: "btn btn-primary" %>
<% end -%>

project_tracking/app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-2">

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @project.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @project.start_date %>
    </p>

    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
  </div>
</div>

project_tracking/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project_tracking/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

project_tracking/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

project_tracking/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

project_tracking/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

project_tracking/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

project_tracking/app/views/welcome/index.html.erb
<h1>Welcome to Project Tracking</h1>
<p>Create, track, and manage all your Projects in one cool application</p>